name: intrusion

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    depends_on:
      - traefik
    networks:
      - traefik-proxy

  website:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`intrusion.localhost`)
      - traefik.http.routers.cafejeux.entrypoints=websecure
      - traefik.http.routers.cafejeux.tls.certresolver=letsencrypt
      - traefik.http.services.website.loadbalancer.server.port=8001
    networks:
      - traefik-proxy

volumes:
  redis-data:

networks:
  traefik-proxy:
    external: true