name: intrusion

services:
  redis:
    image: redis:8.2-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - traefik-proxy

  website:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`intrusion.cmnemoi.com`)
      - traefik.http.routers.website.entrypoints=websecure
      - traefik.http.routers.website.tls.certresolver=letsencrypt
      - traefik.http.services.website.loadbalancer.server.port=8001
    networks:
      - traefik-proxy

volumes:
  redis-data:

networks:
  traefik-proxy:
    external: true